unit test added for #725

diff --git a/.github/workflows/binary.yml b/.github/workflows/binary.yml
--- a/.github/workflows/binary.yml
+++ b/.github/workflows/binary.yml
@@ -40,6 +40,7 @@ jobs:
         curl -L -o binary.in "https://github.com/danieljprice/phantom/releases/download/v2025.0.0/binary.in"
         curl -L -o poly.setup "https://github.com/danieljprice/phantom/releases/download/v2025.0.0/poly.setup"
         curl -L -o poly.in "https://github.com/danieljprice/phantom/releases/download/v2025.0.0/poly.in"
+        curl -L -o sim.setup "https://github.com/danieljprice/phantom/releases/download/v2025.0.0/sim.setup"
         
         # Verify SHA256 hashes (Linux compatible)
         echo "95f9785284a5dc6e23d81991e12086218a4fa40e6449af43d205a8c613da2140  profile9donor.data" | sha256sum -c
@@ -48,6 +49,7 @@ jobs:
         echo "efea56e820e15fbcd4fa47bc62cd7d9b3eb64794906227ba4c2145c431272487  binary.in" | sha256sum -c
         echo "679ee7a3fd9af74063ebec4354c4c4235865aa26e8ee360d5711736839395459  poly.setup" | sha256sum -c
         echo "b7b7a780d22d3ffc1541576f93d18cac811212d03aa6e1992ef1105af80e342f  poly.in" | sha256sum -c
+        echo "f8b0bb9decb74b053b625d67c3df27c48d0f171b23d3e08848d4ef80e271b0dc  sim.setup" | sha256sum -c
 
         # run the test, run phantomsetup 3 times to ensure .setup file is rewritten if necessary
         ./phantomsetup binary.setup
@@ -64,3 +66,10 @@ jobs:
         ./phantomsetup poly.setup
         ./phantomsetup poly.setup
         ./phantom poly.in
+
+        # now also run a test with a polytrope + softened sink (https://github.com/danieljprice/phantom/issues/725)
+        rm relax*
+        ./phantomsetup sim.setup
+        if [ ! -f relax1_00005 ]; then echo "Missing relax1_00005 after phantomsetup"; ls -la; exit 1; fi
+        if [ ! -f sim_00000.tmp ]; then echo "Missing sim_00000.tmp after phantomsetup"; ls -la; exit 1; fi
+        if [ ! -f sim.in ]; then echo "Missing sim.in after phantomsetup"; ls -la; exit 1; fi
