cache intel installation

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -62,8 +62,19 @@ jobs:
         rm GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB
         sudo echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
         sudo apt-get update
+        INTELVERSION=$(apt-cache show <packageName> | grep Version | head -1)
+        echo "::set-env name=INTELVERSION::$INTELVERSION"
+
+    - name: Cache intel installation
+      id: cache-intel
+      uses: actions/cache@v2
+      with:
+        path: |
+          /opt/intel
+        key: ${{ runner.os }}-${{ env.INTELVERSION }}
 
     - name: Install Intel compilers
+      if: steps.cache-intel.outputs.cache-hit != 'true'
       run: |
         sudo apt-get install -y intel-oneapi-common-vars
         sudo apt-get install -y intel-oneapi-compiler-fortran
@@ -71,63 +82,66 @@ jobs:
         sudo apt-get install -y intel-oneapi-mpi
         sudo apt-get install -y intel-oneapi-mpi-devel
 
-    - name: "Clone phantom"
-      uses: actions/checkout@v2
-
-    - name: "Grab a copy of splash source code"
-      uses: actions/checkout@v2
-      with:
-        repository: danieljprice/splash
-        path: splash
-
-    - name: "Create logs directory"
-      run: mkdir logs
-
-    - name: "Grab previous build logs from web server"
-      env:
-        WGET: wget --recursive --no-parent --reject "index.html*" --cut-dirs=2 --no-host-directories
-      run: ${WGET} -A '*${{ matrix.system[1] }}.txt' http://${WEB_SERVER}${BUILD_LOG_DIR}/ || true
-
-    - name: "Run buildbot.sh"
+    - name: Setup Intel oneAPI environment
       run: |
         source /opt/intel/oneapi/setvars.sh
-        ./buildbot.sh 17000000 http://${WEB_SERVER}/${BUILD_LOG_DIR}
-      working-directory: scripts
-      env:
-        SYSTEM: ${{ matrix.system[1] }}
-        RETURN_ERR: yes
+        printenv >> $GITHUB_ENV
 
-    - name: "Install SSH Key"
-      if: github.event_name == 'schedule'
-      uses: webfactory/ssh-agent@v0.5.3
-      with:
-        ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}
+    # - name: "Clone phantom"
+    #   uses: actions/checkout@v2
 
-    - name: "Copy new build logs to web server"
-      if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
-      run: rsync -vau logs/*.txt ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}
+    # - name: "Grab a copy of splash source code"
+    #   uses: actions/checkout@v2
+    #   with:
+    #     repository: danieljprice/splash
+    #     path: splash
 
-    - name: "Copy HTML files to web server"
-      if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
-      run: |
-        export WEB_BUILD_DIR=${WEB_HTML_DIR}/nightly/build/$(date "+%Y%m%d")
-        ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" ${WEB_USER}@${WEB_SERVER} -- mkdir -p ${WEB_BUILD_DIR}
-        rsync -vau logs/*.html ${WEB_USER}@${WEB_SERVER}:${WEB_BUILD_DIR}/
+    # - name: "Create logs directory"
+    #   run: mkdir logs
 
-    - name: logs/build-failures-${{ matrix.system[1] }}.txt
-      if: always()
-      run: cat logs/build-failures-${{ matrix.system[1] }}.txt || true
+    # - name: "Grab previous build logs from web server"
+    #   env:
+    #     WGET: wget --recursive --no-parent --reject "index.html*" --cut-dirs=2 --no-host-directories
+    #   run: ${WGET} -A '*${{ matrix.system[1] }}.txt' http://${WEB_SERVER}${BUILD_LOG_DIR}/ || true
 
-    - name: logs/setup-failures-${{ matrix.system[1] }}.txt
-      if: always()
-      run: cat logs/setup-failures-${{ matrix.system[1] }}.txt || true
+    # - name: "Run buildbot.sh"
+    #   run: | ./buildbot.sh 17000000 http://${WEB_SERVER}/${BUILD_LOG_DIR}
+    #   working-directory: scripts
+    #   env:
+    #     SYSTEM: ${{ matrix.system[1] }}
+    #     RETURN_ERR: yes
 
-    - name: logs/make-*-${{ matrix.system[1] }}.txt
-      if: always()
-      run: |
-        echo
-        for item in $(ls logs/make-*-${{ matrix.system[1] }}.txt); do
-          echo ::group::"${item}"
-          cat $item
-          echo ::endgroup::
-        done
+    # - name: "Install SSH Key"
+    #   if: github.event_name == 'schedule'
+    #   uses: webfactory/ssh-agent@v0.5.3
+    #   with:
+    #     ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}
+
+    # - name: "Copy new build logs to web server"
+    #   if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
+    #   run: rsync -vau logs/*.txt ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}
+
+    # - name: "Copy HTML files to web server"
+    #   if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
+    #   run: |
+    #     export WEB_BUILD_DIR=${WEB_HTML_DIR}/nightly/build/$(date "+%Y%m%d")
+    #     ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" ${WEB_USER}@${WEB_SERVER} -- mkdir -p ${WEB_BUILD_DIR}
+    #     rsync -vau logs/*.html ${WEB_USER}@${WEB_SERVER}:${WEB_BUILD_DIR}/
+
+    # - name: logs/build-failures-${{ matrix.system[1] }}.txt
+    #   if: always()
+    #   run: cat logs/build-failures-${{ matrix.system[1] }}.txt || true
+
+    # - name: logs/setup-failures-${{ matrix.system[1] }}.txt
+    #   if: always()
+    #   run: cat logs/setup-failures-${{ matrix.system[1] }}.txt || true
+
+    # - name: logs/make-*-${{ matrix.system[1] }}.txt
+    #   if: always()
+    #   run: |
+    #     echo
+    #     for item in $(ls logs/make-*-${{ matrix.system[1] }}.txt); do
+    #       echo ::group::"${item}"
+    #       cat $item
+    #       echo ::endgroup::
+    #     done
