Parallel build action (#224)
Type of PR:
other

Description:
The build check action makes each configuration sequentially. Currently there are 93 setups, so this takes about 3 hours to finish. This test slows down development pace because developers must wait a long time for checks on pull requests.

While waiting for build checks on my other PRs to finish, I parallelised the build action 😄

The maximum github action matrix size is 128. The tests cannot be run individually because all 93 tests have to be run for each compiler, >128. buildbot.sh has been modified to run setups in batches. It takes the argument

./buildbot.sh --parallel i j
where j is the number of batches to split the setups into, and the i'th batch is run. For example, --parallel 2 10 will split the setups into 10 batches, and run the 2nd one. To run all the setups, the command must be called j times, for i=1 to i=j. This is split across github runners.

j is set to 32. Using the github runner (for gfortran compiler), the entire build test runs in ~12 minutes, which is ~15x faster. The ifort compiler will be bottlenecked by the number of available custom runners.

A summary job is added to the end of all workflows with a matrix so that the branch protection requirement does not need to be changed when the matrix changes. The requirements build, mpi, test will now cover all tests. Resolves #226

Testing:
build test continues to run all setups

Did you run the bots? no - not required

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -23,6 +23,7 @@ env:
   WEB_HTML_DIR: /var/www/html
   BUILD_LOG_DIR: /ci/build/logs
   RSYNC_RSH: ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null"
+  NPARALLEL: 32
 
 jobs:
   matrix_prep:
@@ -30,6 +31,8 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
+      batch: ${{ steps.set-sequence.outputs.batch }}
+      nbatch: ${{ steps.set-sequence.outputs.nbatch }}
     steps:
     - name: Check out repo
       uses: actions/checkout@v2
@@ -38,6 +41,17 @@ jobs:
       with:
         inputFile: '.github/workflows/matrix_system.json'
         filter: '["${{ github.repository }}", "always"]'
+    - name: Generate sequence of batch numbers for normal tests, or run sequentially for scheduled tests
+      id: set-sequence
+      run: |
+        if [[ ${{ github.event_name == 'schedule' }} ]]; then
+          range=$(jq -ncR "[range(1;${NPARALLEL}+1)]")
+          echo "::set-output name=batch::${range}"
+          echo "::set-output name=nbatch::${NPARALLEL}"
+        else
+          echo "::set-output name=batch::[1]"
+          echo "::set-output name=nbatch::1"
+        fi
 
   build:
     needs: matrix_prep
@@ -45,8 +59,10 @@ jobs:
       fail-fast: false
       matrix:
         system: ${{ fromJson(needs.matrix_prep.outputs.matrix).include }}
+        batch: ${{ fromJson(needs.matrix_prep.outputs.batch) }}
 
-    name: build (SYSTEM=${{ matrix.system[1] }})
+
+    name: build (batch ${{ matrix.batch }}/${{ needs.matrix_prep.outputs.nbatch }}, SYSTEM=${{ matrix.system[1] }})
 
     runs-on: ${{ matrix.system[0] }}
 
@@ -65,15 +81,17 @@ jobs:
         path: splash
 
     - name: "Create logs directory"
+      if: github.event_name == 'schedule'
       run: mkdir logs
 
     - name: "Grab previous build logs from web server"
+      if: github.event_name == 'schedule'
       env:
         WGET: wget --recursive --no-parent --reject "index.html*" --cut-dirs=2 --no-host-directories
       run: ${WGET} -A '*${{ matrix.system[1] }}.txt' http://${WEB_SERVER}${BUILD_LOG_DIR}/ || true
 
     - name: "Run buildbot.sh"
-      run: ./buildbot.sh 17000000 http://${WEB_SERVER}/${BUILD_LOG_DIR}
+      run: ./buildbot.sh --maxdim 17000000 --url http://${WEB_SERVER}/${BUILD_LOG_DIR} --parallel ${{ matrix.batch }} ${{ env.NPARALLEL }}
       working-directory: scripts
       env:
         SYSTEM: ${{ matrix.system[1] }}
@@ -113,3 +131,25 @@ jobs:
           cat $item
           echo ::endgroup::
         done
+
+  # Gather results into a dummy job that will fail if the previous job fails
+  gather_results:
+    if: always()
+    needs:
+    - build
+
+    # This name matches the branch protection requirement
+    name: build
+
+    # Always run on github runner; no need to use custom runner for the check
+    runs-on: ubuntu-latest
+
+    steps:
+    - name: Check all builds
+      run: |
+        if [[ "${{ needs.build.result }}" == "success" ]]; then
+          echo "All build succeeded"
+        else
+          echo "At least one build failed"
+          exit 1
+        fi
