run an empty build step
to add the job name into git's branch protection history

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -53,90 +53,90 @@ jobs:
           echo "::set-output name=nbatch::1"
         fi
 
-  build:
-    needs: matrix_prep
-    strategy:
-      fail-fast: false
-      matrix:
-        system: ${{ fromJson(needs.matrix_prep.outputs.matrix).include }}
-        batch: ${{ fromJson(needs.matrix_prep.outputs.batch) }}
+  # build:
+  #   needs: matrix_prep
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       system: ${{ fromJson(needs.matrix_prep.outputs.matrix).include }}
+  #       batch: ${{ fromJson(needs.matrix_prep.outputs.batch) }}
 
 
-    name: build (batch ${{ matrix.batch }}/${{ needs.matrix_prep.outputs.nbatch }}, SYSTEM=${{ matrix.system[1] }})
+  #   name: build (batch ${{ matrix.batch }}/${{ needs.matrix_prep.outputs.nbatch }}, SYSTEM=${{ matrix.system[1] }})
 
-    runs-on: ${{ matrix.system[0] }}
+  #   runs-on: ${{ matrix.system[0] }}
 
-    steps:
+  #   steps:
 
-    - name: "Nuke the github workspace before doing anything"
-      run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}
+  #   - name: "Nuke the github workspace before doing anything"
+  #     run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}
 
-    - name: "Clone phantom"
-      uses: actions/checkout@v2
+  #   - name: "Clone phantom"
+  #     uses: actions/checkout@v2
 
-    - name: "Grab a copy of splash source code"
-      uses: actions/checkout@v2
-      with:
-        repository: danieljprice/splash
-        path: splash
+  #   - name: "Grab a copy of splash source code"
+  #     uses: actions/checkout@v2
+  #     with:
+  #       repository: danieljprice/splash
+  #       path: splash
 
-    - name: "Create logs directory"
-      if: github.event_name == 'schedule'
-      run: mkdir logs
+  #   - name: "Create logs directory"
+  #     if: github.event_name == 'schedule'
+  #     run: mkdir logs
 
-    - name: "Grab previous build logs from web server"
-      if: github.event_name == 'schedule'
-      env:
-        WGET: wget --recursive --no-parent --reject "index.html*" --cut-dirs=2 --no-host-directories
-      run: ${WGET} -A '*${{ matrix.system[1] }}.txt' http://${WEB_SERVER}${BUILD_LOG_DIR}/ || true
+  #   - name: "Grab previous build logs from web server"
+  #     if: github.event_name == 'schedule'
+  #     env:
+  #       WGET: wget --recursive --no-parent --reject "index.html*" --cut-dirs=2 --no-host-directories
+  #     run: ${WGET} -A '*${{ matrix.system[1] }}.txt' http://${WEB_SERVER}${BUILD_LOG_DIR}/ || true
 
-    - name: "Run buildbot.sh"
-      run: ./buildbot.sh --maxdim 17000000 --url http://${WEB_SERVER}/${BUILD_LOG_DIR} --parallel ${{ matrix.batch }} ${{ env.NPARALLEL }}
-      working-directory: scripts
-      env:
-        SYSTEM: ${{ matrix.system[1] }}
-        RETURN_ERR: yes
+  #   - name: "Run buildbot.sh"
+  #     run: ./buildbot.sh --maxdim 17000000 --url http://${WEB_SERVER}/${BUILD_LOG_DIR} --parallel ${{ matrix.batch }} ${{ env.NPARALLEL }}
+  #     working-directory: scripts
+  #     env:
+  #       SYSTEM: ${{ matrix.system[1] }}
+  #       RETURN_ERR: yes
 
-    - name: "Install SSH Key"
-      if: github.event_name == 'schedule'
-      uses: webfactory/ssh-agent@v0.5.3
-      with:
-        ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}
+  #   - name: "Install SSH Key"
+  #     if: github.event_name == 'schedule'
+  #     uses: webfactory/ssh-agent@v0.5.3
+  #     with:
+  #       ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}
 
-    - name: "Copy new build logs to web server"
-      if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
-      run: rsync -vau logs/*.txt ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}
+  #   - name: "Copy new build logs to web server"
+  #     if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
+  #     run: rsync -vau logs/*.txt ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}
 
-    - name: "Copy HTML files to web server"
-      if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
-      run: |
-        export WEB_BUILD_DIR=${WEB_HTML_DIR}/nightly/build/$(date "+%Y%m%d")
-        ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" ${WEB_USER}@${WEB_SERVER} -- mkdir -p ${WEB_BUILD_DIR}
-        rsync -vau logs/*.html ${WEB_USER}@${WEB_SERVER}:${WEB_BUILD_DIR}/
+  #   - name: "Copy HTML files to web server"
+  #     if: ${{ (success() || failure()) && github.event_name == 'schedule' }}
+  #     run: |
+  #       export WEB_BUILD_DIR=${WEB_HTML_DIR}/nightly/build/$(date "+%Y%m%d")
+  #       ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" ${WEB_USER}@${WEB_SERVER} -- mkdir -p ${WEB_BUILD_DIR}
+  #       rsync -vau logs/*.html ${WEB_USER}@${WEB_SERVER}:${WEB_BUILD_DIR}/
 
-    - name: logs/build-failures-${{ matrix.system[1] }}.txt
-      if: always()
-      run: cat logs/build-failures-${{ matrix.system[1] }}.txt || true
+  #   - name: logs/build-failures-${{ matrix.system[1] }}.txt
+  #     if: always()
+  #     run: cat logs/build-failures-${{ matrix.system[1] }}.txt || true
 
-    - name: logs/setup-failures-${{ matrix.system[1] }}.txt
-      if: always()
-      run: cat logs/setup-failures-${{ matrix.system[1] }}.txt || true
+  #   - name: logs/setup-failures-${{ matrix.system[1] }}.txt
+  #     if: always()
+  #     run: cat logs/setup-failures-${{ matrix.system[1] }}.txt || true
 
-    - name: logs/make-*-${{ matrix.system[1] }}.txt
-      if: always()
-      run: |
-        echo
-        for item in $(ls logs/make-*-${{ matrix.system[1] }}.txt); do
-          echo ::group::"${item}"
-          cat $item
-          echo ::endgroup::
-        done
+  #   - name: logs/make-*-${{ matrix.system[1] }}.txt
+  #     if: always()
+  #     run: |
+  #       echo
+  #       for item in $(ls logs/make-*-${{ matrix.system[1] }}.txt); do
+  #         echo ::group::"${item}"
+  #         cat $item
+  #         echo ::endgroup::
+  #       done
 
   # Gather results into a dummy job that will fail if the previous job fails
   gather_results:
     if: always()
-    needs:
-    - build
+    # needs:
+    # - build
 
     # This name matches the branch protection requirement
     name: build
@@ -145,11 +145,12 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Check all builds succeeded
-      run: |
-        if [[ "${{ needs.build.result }}" == "success" ]]; then
-          echo "All build succeeded"
-        else
-          echo "At least one build failed"
-          exit 1
-        fi
+    - run: echo "ok"
+    # - name: Check all builds succeeded
+    #   run: |
+    #     if [[ "${{ needs.build.result }}" == "success" ]]; then
+    #       echo "All build succeeded"
+    #     else
+    #       echo "At least one build failed"
+    #       exit 1
+    #     fi
