debug ssh key

diff --git a/.github/workflows/build-bot.yml b/.github/workflows/build-bot.yml
--- a/.github/workflows/build-bot.yml
+++ b/.github/workflows/build-bot.yml
@@ -31,62 +31,65 @@ jobs:
 
     steps:
 
-    - name: "Install SSH Key"
-      uses: webfactory/ssh-agent@v0.5.3
-      with:
-        ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}
+    - name: "Debug SSH key"
+      run: echo ${{ secrets.RUNNER_PRIVATE_KEY }}
 
-    - name: "Nuke the github workspace before doing anything"
-      run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}
+    # - name: "Install SSH Key"
+    #   uses: webfactory/ssh-agent@v0.5.3
+    #   with:
+    #     ssh-private-key: ${{ secrets.RUNNER_PRIVATE_KEY }}
 
-    - name: "Clone phantom"
-      uses: actions/checkout@v2
+    # - name: "Nuke the github workspace before doing anything"
+    #   run: rm -r ${{ github.workspace }} && mkdir ${{ github.workspace }}
 
-    - name: "Grab a copy of splash source code"
-      uses: actions/checkout@v2
-      with:
-        repository: danieljprice/splash
-        path: splash
+    # - name: "Clone phantom"
+    #   uses: actions/checkout@v2
 
-    - name: "Create logs directory"
-      run: mkdir logs
+    # - name: "Grab a copy of splash source code"
+    #   uses: actions/checkout@v2
+    #   with:
+    #     repository: danieljprice/splash
+    #     path: splash
 
-    - name: "Grab previous build logs from web server"
-      working-directory: logs
-      run: rsync -vau ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}/*${{ matrix.system[1] }}.txt . || true
+    # - name: "Create logs directory"
+    #   run: mkdir logs
 
-    - name: "Run buildbot.sh"
-      run: ./buildbot.sh 17000000 http://${WEB_SERVER}/${BUILD_LOG_DIR}
-      working-directory: scripts
-      env:
-        SYSTEM: ${{ matrix.system[1] }}
-        RETURN_ERR: yes
+    # - name: "Grab previous build logs from web server"
+    #   working-directory: logs
+    #   run: rsync -vau ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}/*${{ matrix.system[1] }}.txt . || true
 
-    - name: "Copy new build logs to web server"
-      if: always()
-      run: rsync -vau logs/*.txt ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}
+    # - name: "Run buildbot.sh"
+    #   run: ./buildbot.sh 17000000 http://${WEB_SERVER}/${BUILD_LOG_DIR}
+    #   working-directory: scripts
+    #   env:
+    #     SYSTEM: ${{ matrix.system[1] }}
+    #     RETURN_ERR: yes
 
-    - name: "Copy HTML files to web server"
-      if: always()
-      run: |
-        export WEB_BUILD_DIR=${WEB_HTML_DIR}/nightly/build/$(date "+%Y%m%d")
-        ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" ${WEB_USER}@${WEB_SERVER} -- mkdir -p ${WEB_BUILD_DIR}
-        rsync -vau logs/*.html ${WEB_USER}@${WEB_SERVER}:${WEB_BUILD_DIR}/
+    # - name: "Copy new build logs to web server"
+    #   if: always()
+    #   run: rsync -vau logs/*.txt ${WEB_USER}@${WEB_SERVER}:${WEB_HTML_DIR}/${BUILD_LOG_DIR}
 
-    - name: logs/build-failures-${{ matrix.system[1] }}.txt
-      if: always()
-      run: cat logs/build-failures-${{ matrix.system[1] }}.txt || true
+    # - name: "Copy HTML files to web server"
+    #   if: always()
+    #   run: |
+    #     export WEB_BUILD_DIR=${WEB_HTML_DIR}/nightly/build/$(date "+%Y%m%d")
+    #     ssh -o "StrictHostKeyChecking=no" -o "UserKnownHostsFile=/dev/null" ${WEB_USER}@${WEB_SERVER} -- mkdir -p ${WEB_BUILD_DIR}
+    #     rsync -vau logs/*.html ${WEB_USER}@${WEB_SERVER}:${WEB_BUILD_DIR}/
 
-    - name: logs/setup-failures-${{ matrix.system[1] }}.txt
-      if: always()
-      run: cat logs/setup-failures-${{ matrix.system[1] }}.txt || true
+    # - name: logs/build-failures-${{ matrix.system[1] }}.txt
+    #   if: always()
+    #   run: cat logs/build-failures-${{ matrix.system[1] }}.txt || true
 
-    - name: logs/make-*-${{ matrix.system[1] }}.txt
-      if: always()
-      run: |
-        echo
-        for item in $(ls logs/make-*-${{ matrix.system[1] }}.txt); do
-          echo ::group::"${item}"
-          cat $item
-          echo ::endgroup::
-        done
+    # - name: logs/setup-failures-${{ matrix.system[1] }}.txt
+    #   if: always()
+    #   run: cat logs/setup-failures-${{ matrix.system[1] }}.txt || true
+
+    # - name: logs/make-*-${{ matrix.system[1] }}.txt
+    #   if: always()
+    #   run: |
+    #     echo
+    #     for item in $(ls logs/make-*-${{ matrix.system[1] }}.txt); do
+    #       echo ::group::"${item}"
+    #       cat $item
+    #       echo ::endgroup::
+    #     done
